### ISSUE TITLE
installing network2tikz adds an old pathpy version

### ISSUE THREAD

**Issue by user1246638** [hackl/network2tikz#4]
I am unsure whether this is a network2tikz issue or a pip issue.

I have pathpy installed in editable form.
When I install network2tikz, it adds a pathpy folder in anaconda\lib\site-packages\ which contains the old version of pathpy. This version then takes priority over the new version that I have.

I checked it two times, and also tried it at my colleague's computer. Installation adds a pathpy folder, and one needs to delete this folder after installing network2tikz in order to have the right version.

**Comment by hackl** [comment]
Thanks for the hint. Indeed something went wrong with the package dependencies. I fixed this issue. Now only network2tikz without any other supported network modules should be installed.

**Comment by user1246638** [comment]
Thanks!
